#!/usr/bin/env python3
"""train_fno.py - Train FNO or CNN on spectral super-resolution task.

Loads (coarse, fine) field pairs generated by Fortran, trains a model to
predict the residual (fine - coarse), and evaluates reconstruction quality
in both physical and spectral space.

Usage:
    python train_fno.py                            # Train FNO with defaults
    python train_fno.py --model cnn                # Train CNN baseline
    python train_fno.py --epochs 200 --lr 1e-3     # Custom training
    python train_fno.py --data-dir ../experiments/001_synthetic_2d/fields/

This is an experiment tool, not a production trainer. Quick and readable.
"""

import argparse
import json
import struct
import time
from datetime import datetime
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from models.fno_2d import FNO2d, SimpleCNN
from torch.utils.data import DataLoader, Dataset


class TurbulenceDataset(Dataset):
    """Load (coarse, fine) field pairs from Fortran binary output."""

    def __init__(self, data_dir, n_samples=None):
        self.data_dir = Path(data_dir)

        # Find all sample pairs
        fine_files = sorted(self.data_dir.glob("fine_sample_*.bin"))
        if n_samples:
            fine_files = fine_files[:n_samples]

        self.samples = []
        for fine_file in fine_files:
            sample_id = fine_file.stem.replace("fine_sample_", "")
            coarse_file = self.data_dir / f"coarse_sample_{sample_id}.bin"
            if coarse_file.exists():
                self.samples.append((coarse_file, fine_file))

        print(f"  Loaded {len(self.samples)} sample pairs from {data_dir}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        coarse_file, fine_file = self.samples[idx]
        coarse = self._load_field(coarse_file)
        fine = self._load_field(fine_file)
        residual = fine - coarse  # Model predicts this
        return torch.from_numpy(coarse), torch.from_numpy(residual)

    @staticmethod
    def _load_field(filepath):
        with open(filepath, "rb") as f:
            nx = struct.unpack("i", f.read(4))[0]
            ny = struct.unpack("i", f.read(4))[0]
            data = np.frombuffer(f.read(nx * ny * 4), dtype=np.float32)
            return data.reshape((ny, nx))


def spectral_loss(pred, target, weight_high_k=2.0):
    """Loss that emphasizes high-frequency content in spectral space.

    Standard MSE treats all spatial frequencies equally. But we specifically
    want to recover high-k modes, so we weight them more heavily.
    """
    # Physical space MSE
    mse = nn.functional.mse_loss(pred, target)

    # Spectral space loss
    pred_fft = torch.fft.rfft2(pred)
    target_fft = torch.fft.rfft2(target)

    # Weight by wavenumber (higher k -> higher weight)
    ny, nx_half = pred_fft.shape[-2], pred_fft.shape[-1]
    ky = torch.fft.fftfreq(ny, device=pred.device).abs()
    kx = torch.linspace(0, 0.5, nx_half, device=pred.device)
    KX, KY = torch.meshgrid(ky, kx, indexing="ij")
    K = torch.sqrt(KX**2 + KY**2)

    # Weight: 1 at low-k, weight_high_k at high-k
    weights = 1.0 + (weight_high_k - 1.0) * K / K.max()

    spectral_mse = torch.mean(weights * torch.abs(pred_fft - target_fft) ** 2)

    return mse + 0.1 * spectral_mse


def compute_spectrum_numpy(field):
    """Compute 1D energy spectrum from 2D field (numpy, for evaluation)."""
    ny, nx = field.shape
    fft = np.fft.rfft2(field)
    power = np.abs(fft) ** 2 / (nx * ny) ** 2

    nkx = nx // 2 + 1
    k_max = min(nx, ny) // 2
    E_k = np.zeros(k_max)
    counts = np.zeros(k_max)

    for j in range(ny):
        ky = j if j <= ny // 2 else j - ny
        for i in range(nkx):
            kx = i
            k_mag = np.sqrt(kx**2 + ky**2)
            bin_idx = int(k_mag)
            if 0 <= bin_idx < k_max:
                e = power[j, i]
                if i > 0 and i < nkx - 1:
                    e *= 2  # R2C symmetry
                E_k[bin_idx] += e
                counts[bin_idx] += 1

    k_vals = np.arange(k_max, dtype=np.float32)
    return k_vals, E_k


def train(args):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"\n  Device: {device}")

    # Load data
    dataset = TurbulenceDataset(args.data_dir, n_samples=args.n_samples)

    # Train/val split
    n_val = max(1, len(dataset) // 5)
    n_train = len(dataset) - n_val
    train_set, val_set = torch.utils.data.random_split(
        dataset, [n_train, n_val], generator=torch.Generator().manual_seed(42)
    )

    train_loader = DataLoader(train_set, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=args.batch_size, shuffle=False)

    print(f"  Train: {n_train}, Val: {n_val}")

    # Model
    if args.model == "fno":
        model = FNO2d(
            modes1=args.modes,
            modes2=args.modes,
            width=args.width,
            n_layers=args.n_layers,
        ).to(device)
    else:
        model = SimpleCNN(n_channels=args.width, n_layers=args.n_layers).to(device)

    print(f"  Model: {args.model.upper()}, Parameters: {model.count_params():,}")

    optimizer = optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, args.epochs)

    # Training loop
    best_val_loss = float("inf")
    history = {"train_loss": [], "val_loss": [], "lr": []}

    t_start = time.time()

    for epoch in range(1, args.epochs + 1):
        # Train
        model.train()
        train_loss = 0
        for coarse, residual in train_loader:
            coarse, residual = coarse.to(device), residual.to(device)

            pred = model(coarse)

            if args.spectral_loss:
                loss = spectral_loss(pred, residual)
            else:
                loss = nn.functional.mse_loss(pred, residual)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        train_loss /= len(train_loader)

        # Validate
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for coarse, residual in val_loader:
                coarse, residual = coarse.to(device), residual.to(device)
                pred = model(coarse)
                val_loss += nn.functional.mse_loss(pred, residual).item()
        val_loss /= len(val_loader)

        scheduler.step()

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["lr"].append(optimizer.param_groups[0]["lr"])

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), args.output_dir / "best_model.pt")

        if epoch % args.print_every == 0 or epoch == 1:
            elapsed = time.time() - t_start
            print(
                f"  Epoch {epoch:4d}/{args.epochs} | "
                f"Train: {train_loss:.6f} | Val: {val_loss:.6f} | "
                f"Best: {best_val_loss:.6f} | "
                f"LR: {optimizer.param_groups[0]['lr']:.2e} | "
                f"Time: {elapsed:.1f}s"
            )

    total_time = time.time() - t_start
    print(f"\n  Training complete in {total_time:.1f}s")
    print(f"  Best validation loss: {best_val_loss:.6f}")

    # Save training history
    with open(args.output_dir / "training_history.json", "w") as f:
        json.dump(history, f)

    # Evaluate on one sample
    model.load_state_dict(
        torch.load(args.output_dir / "best_model.pt", weights_only=True)
    )
    model.eval()

    with torch.no_grad():
        coarse, residual = dataset[0]
        coarse, residual = (
            coarse.unsqueeze(0).to(device),
            residual.unsqueeze(0).to(device),
        )
        pred_residual = model(coarse)

        # Reconstruct
        fine_true = coarse + residual
        fine_pred = coarse + pred_residual

        # Move to numpy
        fine_true_np = fine_true.squeeze().cpu().numpy()
        fine_pred_np = fine_pred.squeeze().cpu().numpy()
        coarse_np = coarse.squeeze().cpu().numpy()

    # Spectral comparison
    k_true, E_true = compute_spectrum_numpy(fine_true_np)
    k_pred, E_pred = compute_spectrum_numpy(fine_pred_np)
    k_coarse, E_coarse = compute_spectrum_numpy(coarse_np)

    # Save spectra for plotting
    np.savetxt(
        args.output_dir / "spectrum_true.dat",
        np.column_stack([k_true, E_true]),
        header="k E(k)",
    )
    np.savetxt(
        args.output_dir / "spectrum_predicted.dat",
        np.column_stack([k_pred, E_pred]),
        header="k E(k)",
    )
    np.savetxt(
        args.output_dir / "spectrum_coarse.dat",
        np.column_stack([k_coarse, E_coarse]),
        header="k E(k)",
    )

    # Summary
    mse_reconstruction = np.mean((fine_true_np - fine_pred_np) ** 2)
    mse_coarse_only = np.mean((fine_true_np - coarse_np) ** 2)
    improvement = 1.0 - mse_reconstruction / mse_coarse_only

    summary = {
        "model": args.model,
        "parameters": model.count_params(),
        "epochs": args.epochs,
        "best_val_loss": best_val_loss,
        "mse_reconstruction": float(mse_reconstruction),
        "mse_coarse_only": float(mse_coarse_only),
        "improvement_pct": float(improvement * 100),
        "training_time_s": total_time,
        "timestamp": datetime.now().isoformat(),
    }

    with open(args.output_dir / "summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    print(f"\n  Results:")
    print(f"    MSE (coarse only):   {mse_coarse_only:.6f}")
    print(f"    MSE (with model):    {mse_reconstruction:.6f}")
    print(f"    Improvement:         {improvement * 100:.1f}%")
    print(f"\n  Output saved to: {args.output_dir}")


def main():
    parser = argparse.ArgumentParser(
        description="Train FNO for spectral super-resolution"
    )
    parser.add_argument("--model", type=str, default="fno", choices=["fno", "cnn"])
    parser.add_argument(
        "--data-dir", type=str, default="../experiments/001_synthetic_2d/fields/"
    )
    parser.add_argument("--output-dir", type=str, default=None)
    parser.add_argument("--n-samples", type=int, default=None)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument(
        "--modes", type=int, default=12, help="Number of Fourier modes (FNO only)"
    )
    parser.add_argument("--width", type=int, default=32, help="Channel width")
    parser.add_argument("--n-layers", type=int, default=4)
    parser.add_argument(
        "--spectral-loss", action="store_true", help="Use spectral-weighted loss"
    )
    parser.add_argument("--print-every", type=int, default=10)
    args = parser.parse_args()

    # Default output directory
    if args.output_dir is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.output_dir = Path(
            f"../experiments/001_synthetic_2d/runs/{args.model}_{timestamp}"
        )
    else:
        args.output_dir = Path(args.output_dir)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    args.data_dir = Path(args.data_dir)

    # Save config
    with open(args.output_dir / "config.json", "w") as f:
        json.dump(vars(args), f, indent=2, default=str)

    print("=" * 60)
    print("  Spectral Super-Resolution Training")
    print("=" * 60)

    train(args)


if __name__ == "__main__":
    main()
